name: Benchmark Pipeline Test

on:
  push:

concurrency:
  group: benchmark

jobs:
  pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@v7
        with:
          module: "."
          version: "0.15.1"
          args: benchmark-pipeline-test
